import { images } from "@/assets";

export const court = {
  futsal: [
    {
      id: 1,
      name: "Lapangan 1",
      type: "Rumput",
      price: "Rp. 100.000-165.000/jam",
      image: images.Futsal,
      available: true,
    },
    {
      id: 2,
      name: "Lapangan 2",
      type: "Interlok",
      price: "Rp. 85.000-145.000/jam",
      image: images.Futsal,
      available: true,
    },
    {
      id: 3,
      name: "Lapangan 3",
      type: "Rumput",
      price: "Rp. 90.000-155.000/jam",
      image: images.Futsal,
      available: true,
    },
    {
      id: 4,
      name: "Lapangan 4",
      type: "Semen",
      price: "Rp. 70.000-125.000/jam",
      image: images.Futsal,
      available: false,
    },
    {
      id: 5,
      name: "Lapangan 5",
      type: "Semen",
      price: "Rp. 70.000-125.000/jam",
      image: images.Futsal,
      available: true,
    },
    {
      id: 6,
      name: "Lapangan 6",
      type: "Semen",
      price: "Rp. 70.000-125.000/jam",
      image: images.Futsal,
      available: true,
    },
  ],
  badminton: [
    {
      id: 1,
      name: "Lapangan 1",
      price: "Rp. 20.000-30.000/jam",
      image: images.Badminton,
      available: true,
    },
    {
      id: 2,
      name: "Lapangan 2",
      price: "Rp. 20.000-30.000/jam",
      image: images.Badminton,
      available: true,
    },
    {
      id: 3,
      name: "Lapangan 3",
      price: "Rp. 20.000-30.000/jam",
      image: images.Badminton,
      available: true,
    },
    {
      id: 4,
      name: "Lapangan 4",
      price: "Rp. 20.000-30.000/jam",
      image: images.Badminton,
      available: true,
    },
    {
      id: 5,
      name: "Lapangan 5",
      price: "Rp. 20.000-30.000/jam",
      image: images.Badminton,
      available: false,
    },
    {
      id: 6,
      name: "Lapangan 6",
      price: "Rp. 20.000-30.000/jam",
      image: images.Badminton,
      available: true,
    },
    {
      id: 7,
      name: "Lapangan 7",
      price: "Rp. 20.000-30.000/jam",
      image: images.Badminton,
      available: true,
    },
  ],
  tableTennis: [
    {
      id: 1,
      name: "Lapangan 1",
      price: "Rp. 15.000-25.000/jam",
      image: images.TenisMeja,
      available: true,
    },
    {
      id: 2,
      name: "Lapangan 2",
      price: "Rp. 15.000-25.000/jam",
      image: images.TenisMeja,
      available: false,
    },
  ],
};
